# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
# docs: https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions

name: Install DNSControl (cross-platform)
description: Installs DNSControl file into your actions workflow

inputs:
  version:
    description: DNSControl version
    required: true
    default: latest

outputs:
  dnscontrol-bin:
    description: Path to the DNSControl binary file

runs:
  using: node20
  main: dist/index.js

branding:
  icon: arrow-down
  color: green
